# GBM 2026 Testnet Verification Hub
[METADATA]
modified = 2026-03-23T14:15:00Z
network = "testnet"

[[ACCOUNTS]]
address = "rMUFacq4E3ov1q1rhUnkBUnPDqAKpMeeRC"
desc = "Operational Manager Account"

[[ACCOUNTS]]
address = "rD5diNnZon3ahbkrmsiYYrsM2HhZJAhMc"
desc = "GBM Minting Vault"

[[PRINCIPALS]]
name = "Genesiscodefied"
